In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import gensim.downloader as api
from gensim.models import (
    Word2Vec,
    KeyedVectors
)
from gensim.utils import simple_preprocess

import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import sklearn.metrics as metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../../../data/news_data.csv")
df.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [3]:
subject_encoder = LabelEncoder()
df['subject'] = subject_encoder.fit_transform(df['subject'])
df['subject']

0        6
1        6
2        6
3        6
4        6
        ..
44893    1
44894    1
44895    1
44896    1
44897    1
Name: subject, Length: 44898, dtype: int64

In [4]:
df['date'] = pd.to_datetime(df['date'], errors='coerce', format='mixed')
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df.drop(columns=['date'], inplace=True)
df.head()

,title,text,subject,label,year,month,day
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,6,1,2017.0,12.0,31.0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,6,1,2017.0,12.0,29.0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,6,1,2017.0,12.0,31.0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,6,1,2017.0,12.0,30.0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,6,1,2017.0,12.0,29.0

In [5]:
print("Example:\n=====")
print(df['text'][0][:250]+"...")

print("\nPreprocessed:\n=====")
print(' '.join(simple_preprocess(df['text'][0]))[:250]+"...")

Example:
=====
WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint...

Preprocessed:
=====
washington reuters the head of conservative republican faction in the congress who voted this month for huge expansion of the national debt to pay for tax cuts called himself fiscal conservative on sunday and urged budget restraint in in keeping with...

In [6]:
df['title'] = df['title'].apply(lambda x: ' '.join(simple_preprocess(x)))
df['text'] = df['text'].apply(lambda x: ' '.join(simple_preprocess(x)))
df.head()

,title,text,subject,label,year,month,day
0,as budget fight looms republicans flip their f...,washington reuters the head of conservative re...,6,1,2017.0,12.0,31.0
1,military to accept transgender recruits on mon...,washington reuters transgender people will be ...,6,1,2017.0,12.0,29.0
2,senior republican senator let mr mueller do hi...,washington reuters the special counsel investi...,6,1,2017.0,12.0,31.0
3,fbi russia probe helped by australian diplomat...,washington reuters trump campaign adviser geor...,6,1,2017.0,12.0,30.0
4,trump wants postal service to charge much more...,seattle washington reuters president donald tr...,6,1,2017.0,12.0,29.0